export const APP_CONFIG = {
  dbName: 'offline_pos_db',
  dbVersion: 9,
  currency: '₹',
  invoicePrefix: 'INV',
  routes: [
    { id: 'dashboard', title: 'Dashboard', icon: 'fa-gauge-high' },
    { id: 'billing', title: 'Billing', icon: 'fa-cart-shopping' },
    { id: 'tables', title: 'Tables', icon: 'fa-chair' },
    { id: 'products', title: 'Products', icon: 'fa-boxes-stacked' },
    { id: 'purchase', title: 'Purchase Entry', icon: 'fa-truck-ramp-box' },
    { id: 'purchase-history', title: 'Purchase History', icon: 'fa-clipboard-list' },
    { id: 'sales', title: 'Sales', icon: 'fa-receipt' },
    { id: 'customers', title: 'Customers', icon: 'fa-users' },
    { id: 'whatsapp-marketing', title: 'WhatsApp Marketing', icon: 'fa-brands fa-whatsapp' },
    { id: 'reports', title: 'Reports', icon: 'fa-chart-line' },
    { id: 'gst-export', title: 'GST Export', icon: 'fa-file-export' },
    { id: 'settings', title: 'Settings', icon: 'fa-gear' },
    { id: 'license', title: 'License', icon: 'fa-id-card' },
    { id: 'printer', title: 'Printer', icon: 'fa-print' },
    { id: 'barcode', title: 'Barcode', icon: 'fa-barcode' },
    { id: 'backup', title: 'Backup', icon: 'fa-database' }
  ],
  roles: ['Owner', 'Manager', 'Cashier', 'Inventory', 'Accountant'],
  roleAccess: {
    Owner: ['*'],
    Manager: ['dashboard', 'billing', 'tables', 'products', 'purchase', 'purchase-history', 'sales', 'customers', 'whatsapp-marketing', 'reports', 'gst-export', 'printer', 'barcode', 'license', 'backup'],
    Cashier: ['dashboard', 'billing', 'tables', 'sales', 'customers', 'barcode'],
    Inventory: ['dashboard', 'products', 'purchase', 'purchase-history', 'barcode', 'backup'],
    Accountant: ['dashboard', 'sales', 'customers', 'purchase-history', 'reports', 'gst-export', 'backup']
  },
  defaultSettings: {
    shop_name: 'Ginsoft POS Store',
    shop_address: 'Main Market Road, India',
    gstin: '29ABCDE1234F1Z5',
    phone: '+91 90000 00000',
    footer_text: 'Thank you. Visit again.',
    paper_size: '80mm',
    printer_theme: 'thermal',
    receipt_header: 'Tax Invoice',
    receipt_footer: 'Thank you. Visit again.',
    receipt_logo: '',
    gst_enabled: 'true',
    bill_prefix: 'INV',
    billing_mode: 'direct',
    weight_enabled: 'false',
    language: 'en',
    web_sync_enabled: 'false',
    hotel_id: 'GIN-HOTEL-0001',
    web_sync_url: 'https://ginsoft.co/api/pos-sync.php',
    web_sync_interval_minutes: '15',
    license_code: '',
    license_check_url: 'https://ginsoft.co/api/license-check.php',
    license_unlock_check_url: 'https://ginsoft.co/api/license-unlock-check.php',
    license_api_url_visible: 'false',
    license_status: 'unlicensed',
    license_customer_id: '',
    license_validity_till: '',
    license_last_checked_at: '',
    license_reason: '',
    license_hotel_locked: 'false',
    licence_approval: '1'
  }
};
